language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin::$(yarn global bin):$PATH
  - yarn global add @plugnet/dev
script:
  - yarn -g plugnet-dev-travis-build
branches:
  only:
  - master
